# Generated by Django 5.0.7 on 2024-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile-images/default.png', null=True, upload_to='profile-images/'),
        ),
    ]
