# Generated by Django 5.0.7 on 2024-07-20 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 16, 4, 31, 791095, tzinfo=datetime.timezone.utc)),
        ),
    ]
