# Generated by Django 5.0.7 on 2024-07-20 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 17, 19, 33, 660013, tzinfo=datetime.timezone.utc)),
        ),
    ]
